### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by wowwood** [wowwood/blue-site#2]
- [ ] write readme.md

- [ ] animate gradients - https://stackoverflow.com/questions/23441060/how-to-animate-gradients-using-css

- [x] dark mode - https://dev.to/whitep4nth3r/the-best-lightdark-mode-theme-toggle-in-javascript-368f

- [ ] change banner accent colour to be under "extra" array, so can be changed in .md files

- [ ]  add more banner colour presets 

- [x] add railmiles widget - https://public.railmiles.me/signatures/e690d4e501eb3dc8f861f7560b803b12.png
  - https://projects.findnerd.com/list/view/How-to-get-the-last-modified-date-of-a-file-before-uploading/25025/

- [x] figure out a way to add build/commit number to footer
    - https://docs.github.com/en/actions/learn-github-actions/variables#passing-values-between-steps-and-jobs-in-a-workflow
  - use GH actions to pipe value to a file, ref that file in the html, done

- [ ] debug menu showing variables

- [x] 404 page

- [ ] optimise the config.toml file
  - https://www.getzola.org/documentation/getting-started/configuration/
